// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2I1WVRPiMRntXcZjD3zlFGZNZ0-B74kE',
    appId: '1:891094418615:web:a27ea1eef1d39e219e7932',
    messagingSenderId: '891094418615',
    projectId: 'krenova-kita',
    authDomain: 'krenova-kita.firebaseapp.com',
    storageBucket: 'krenova-kita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASn_sQlR78nYhqtjuI_3snswJEP-wSEz4',
    appId: '1:891094418615:android:16fa3bff4bfcec559e7932',
    messagingSenderId: '891094418615',
    projectId: 'krenova-kita',
    storageBucket: 'krenova-kita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzl1nedAO3WuawcSDW7U-2yJU6XVVlfsc',
    appId: '1:891094418615:ios:33c32982d035bda29e7932',
    messagingSenderId: '891094418615',
    projectId: 'krenova-kita',
    storageBucket: 'krenova-kita.appspot.com',
    iosClientId: '891094418615-30atb3g1qcre2tcjfhleu26m9jp93sn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.krenova',
  );
}
